import { defineConfig } from "tsup";

const external = [
  "glob",
  "pino",
  "ajv",
  "@aws-sdk/client-s3",
  "@aws-sdk/client-sqs",
  "@aws-sdk/cloudfront-signer",
  "@aws-sdk/s3-presigned-post",
  "@aws-sdk/s3-request-presigner",
  "@azure/storage-blob",
  "@sinclair/typebox",
  "sqs-consumer",
  "bullmq",
  "ioredis",
  "pg",
  "pg-boss",
  "ws",
  "node-cron",
  "mqtt",
  "esbuild",
  "esbuild-plugin-copy",
  "graphql",
  "@apollo/server",
  "@graphql-tools/schema",
  "swagger-typescript-api",
  "zod",
  "handlebars",
  "edge.js",
  "ejs",
  "mustache",
  "fast-json-stringify",
];

export default defineConfig([
  {
    entry: ["src/index.ts"],
    outDir: "lib",
    format: ["esm", "cjs"],
    dts: true,
    sourcemap: true,
    clean: true,
    external,
    splitting: false,
    treeshake: true,
    minify: true,
  },
  {
    entry: ["src/cli.ts"],
    outDir: "lib",
    format: ["esm"],
    dts: false,
    sourcemap: true,
    clean: true,
    external,
    banner: {
      js: "#!/usr/bin/env node",
    },
    splitting: false,
    treeshake: true,
    minify: true,
  },
]);
