export type StaticPluginOptions = {
  /**
   * The file system directory path where the assets are located
   * @example "./tmp/assets" or "public"
   */
  source: string;
  /**
   * The URL path where the assets will be served
   * @example "/assets" or "/public"
   */
  path: string;
};

export type FileAllowedMimeType =
  | "text/html"
  | "text/css"
  | "application/javascript"
  | "application/typescript"
  | "text/jsx"
  | "text/tsx"
  | "application/json"
  | "application/xml"
  | "application/yaml"
  | "text/csv"
  | "text/plain"
  | "text/markdown"
  | "image/png"
  | "image/jpeg"
  | "image/gif"
  | "image/svg+xml"
  | "image/x-icon"
  | "image/webp"
  | "image/avif"
  | "image/bmp"
  | "image/tiff"
  | "image/heic"
  | "image/heif"
  | "video/mp4"
  | "video/webm"
  | "video/x-msvideo"
  | "video/quicktime"
  | "video/x-matroska"
  | "video/x-ms-wmv"
  | "video/x-flv"
  | "video/x-m4v"
  | "video/mpeg"
  | "video/3gpp"
  | "audio/mpeg"
  | "audio/wav"
  | "audio/ogg"
  | "audio/flac"
  | "audio/aac"
  | "audio/mp4"
  | "audio/x-ms-wma"
  | "audio/opus"
  | "audio/midi"
  | "font/woff"
  | "font/woff2"
  | "font/ttf"
  | "font/otf"
  | "application/vnd.ms-fontobject"
  | "application/pdf"
  | "application/msword"
  | "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
  | "application/vnd.ms-excel"
  | "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  | "application/vnd.ms-powerpoint"
  | "application/vnd.openxmlformats-officedocument.presentationml.presentation"
  | "application/vnd.oasis.opendocument.text"
  | "application/vnd.oasis.opendocument.spreadsheet"
  | "application/vnd.oasis.opendocument.presentation"
  | "application/rtf"
  | "application/epub+zip"
  | "application/zip"
  | "application/x-tar"
  | "application/gzip"
  | "application/x-bzip2"
  | "application/x-xz"
  | "application/vnd.rar"
  | "application/x-7z-compressed"
  | "application/wasm"
  | "application/manifest+json"
  | "text/calendar"
  | "text/vcard"
  | "application/sql"
  | "application/x-sh"
  | "application/x-msdos-program"
  | "application/x-msdownload"
  | "application/octet-stream"
  | "application/x-iso9660-image"
  | "application/x-apple-diskimage"
  | "application/vnd.android.package-archive"
  | "application/java-archive"
  | "application/x-shockwave-flash";
