export const mimeTypesMap = new Map<string, string>([
  // text/web
  [".html", "text/html"],
  [".htm", "text/html"],
  [".css", "text/css"],
  [".js", "application/javascript"],
  [".mjs", "application/javascript"],
  [".cjs", "application/javascript"],
  [".ts", "application/typescript"],
  [".jsx", "text/jsx"],
  [".tsx", "text/tsx"],
  [".json", "application/json"],
  [".xml", "application/xml"],
  [".yaml", "application/yaml"],
  [".yml", "application/yaml"],
  [".csv", "text/csv"],
  [".txt", "text/plain"],
  [".md", "text/markdown"],
  [".markdown", "text/markdown"],

  // image
  [".png", "image/png"],
  [".jpg", "image/jpeg"],
  [".jpeg", "image/jpeg"],
  [".gif", "image/gif"],
  [".svg", "image/svg+xml"],
  [".ico", "image/x-icon"],
  [".webp", "image/webp"],
  [".avif", "image/avif"],
  [".bmp", "image/bmp"],
  [".tiff", "image/tiff"],
  [".tif", "image/tiff"],
  [".heic", "image/heic"],
  [".heif", "image/heif"],

  // video
  [".mp4", "video/mp4"],
  [".webm", "video/webm"],
  [".avi", "video/x-msvideo"],
  [".mov", "video/quicktime"],
  [".mkv", "video/x-matroska"],
  [".wmv", "video/x-ms-wmv"],
  [".flv", "video/x-flv"],
  [".m4v", "video/x-m4v"],
  [".mpeg", "video/mpeg"],
  [".mpg", "video/mpeg"],
  [".3gp", "video/3gpp"],

  // audio
  [".mp3", "audio/mpeg"],
  [".wav", "audio/wav"],
  [".ogg", "audio/ogg"],
  [".flac", "audio/flac"],
  [".aac", "audio/aac"],
  [".m4a", "audio/mp4"],
  [".wma", "audio/x-ms-wma"],
  [".opus", "audio/opus"],
  [".mid", "audio/midi"],
  [".midi", "audio/midi"],

  // font
  [".woff", "font/woff"],
  [".woff2", "font/woff2"],
  [".ttf", "font/ttf"],
  [".otf", "font/otf"],
  [".eot", "application/vnd.ms-fontobject"],

  // document
  [".pdf", "application/pdf"],
  [".doc", "application/msword"],
  [
    ".docx",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  ],
  [".xls", "application/vnd.ms-excel"],
  [
    ".xlsx",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  ],
  [".ppt", "application/vnd.ms-powerpoint"],
  [
    ".pptx",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  ],
  [".odt", "application/vnd.oasis.opendocument.text"],
  [".ods", "application/vnd.oasis.opendocument.spreadsheet"],
  [".odp", "application/vnd.oasis.opendocument.presentation"],
  [".rtf", "application/rtf"],
  [".epub", "application/epub+zip"],

  // archives
  [".zip", "application/zip"],
  [".tar", "application/x-tar"],
  [".gz", "application/gzip"],
  [".gzip", "application/gzip"],
  [".bz2", "application/x-bzip2"],
  [".xz", "application/x-xz"],
  [".rar", "application/vnd.rar"],
  [".7z", "application/x-7z-compressed"],

  // other
  [".wasm", "application/wasm"],
  [".map", "application/json"],
  [".webmanifest", "application/manifest+json"],
  [".ics", "text/calendar"],
  [".vcf", "text/vcard"],
  [".sql", "application/sql"],
  [".sh", "application/x-sh"],
  [".bat", "application/x-msdos-program"],
  [".exe", "application/x-msdownload"],
  [".dll", "application/x-msdownload"],
  [".bin", "application/octet-stream"],
  [".iso", "application/x-iso9660-image"],
  [".dmg", "application/x-apple-diskimage"],
  [".apk", "application/vnd.android.package-archive"],
  [".jar", "application/java-archive"],
  [".swf", "application/x-shockwave-flash"],
]);
