#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn format
yarn build:test

echo "Running tests..."

echo "Running tests for Node..."
yarn test

echo "Running tests for Bun..."
yarn test:bun

echo "Running tests for Deno..."
yarn test:deno

echo "Adding changes..."
git add .
