#!/usr/bin/env sh

yarn format

yarn build:prod

echo "Running tests..."

echo "Running tests for Node..."
yarn test

echo "Running tests for Bun..."
yarn test:bun

echo "Running tests for Deno..."
yarn test:deno
