#!/usr/bin/env sh
set -eu

cleanup() {
  yarn docker:worktree:down
}

trap cleanup EXIT HUP INT TERM

yarn docker:worktree:up

yarn format:worktree

yarn build:worktree

echo "Running tests in the portless worktree stack..."
yarn test:all:worktree
